### ISSUE TITLE
Portfolio URL

### ISSUE THREAD

**Issue by jas2996** [ruhacks/hacker-application#10]
Change portfolio URL to personal website. It's more clear that way. Make it optional. Doubt first time hackers have a personal website.

**Comment by jas2996** [comment]
@ktsuench

**Comment by ktsuench** [comment]
Done.

**Comment by ktsuench** [comment]
Will add in the __(Optional)__ notice later when resumes are accepted.

**Comment by jas2996** [comment]
Ok sounds good.
