### ISSUE TITLE
Bug in latest email

### ISSUE THREAD

**Issue by smehtaca** [ruhacks/hacker-application#14]
@ktsuench This button doesn't work,
<img width="599" alt="screen shot 2018-01-07 at 6 49 23 pm" src="https://user-images.githubusercontent.com/10327030/34655658-7f7a4152-f3db-11e7-9d49-e88e6c83c483.png">

**Comment by smehtaca** [comment]
It's in the latest email that was send out todau

**Comment by ktsuench** [comment]
Yea that's not a bug, it's a feature. ;)

Jokes aside, there's not much I can do about it. The email is sent and I can't recall it.
