### ISSUE TITLE
Implement file upload for resumes

### ISSUE THREAD

**Issue by ktsuench** [ruhacks/hacker-application#7]
Currently resumes are not accepted since file uploading is not implemented.

Is it possible to handle the file processing in the react app as well? _Can it behave like a back end application?_

Otherwise looks like we will need a back end to handle the file processing from the file uploaded from the react front end.

**Comment by smehtaca** [comment]
There's a npm package that handles file uploads in reactjs to firebase, will try to set it up today.

**Comment by jas2996** [comment]
So currently, files can't be uploaded at all?

**Comment by smehtaca** [comment]
I think it's currently a link to google drive if I'm not mistaken. IRRC had to remove the conversational form and replace it with a typeform.

**Comment by jas2996** [comment]
I just took a look at it again, I think we completely took out resumes.

**Comment by ktsuench** [comment]
Yep, took it out entirely. The users can submit a link to their resume using the 'other' url field.

**Comment by smehtaca** [comment]
Sorry I was and still am sick so I wasn't able to get to it, I'll have it done tomorrow. Shouldn't really be a problem to implement as the package is well documented.

**Comment by smehtaca** [comment]
I added in the upload functionality but have'nt tested it yet, should work though, might need to setup storage in firebase console

**Comment by ktsuench** [comment]
Will look into that

**Comment by ktsuench** [comment]
Done.
